CREATE TABLE IF NOT EXISTS boughttickets (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ticketId int NOT NULL,
    userId int NOT NULL,
    createdAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ticketId) REFERENCES tickets(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);