CREATE TABLE IF NOT EXISTS reviews (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    eventId int NOT NULL,
    userId int NOT NULL,
    rating int NOT NULL,
    comment varchar(255) NOT NULL,
    createdAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (eventId) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE
);