INSERT INTO roles (id, roleName) VALUES (1, 'buyer');
INSERT INTO `categories`(`categoryName`) VALUES ('Cinema');
INSERT INTO `categories` (`categoryName`) VALUES ('Nature');
INSERT INTO `categories` (`categoryName`) VALUES ('Theather');
INSERT INTO `categories` (`categoryName`) VALUES ('Expo');
INSERT INTO `categories` (`categoryName`) VALUES ('Automotive');
INSERT INTO tickettypes (ticketName, typePrice) VALUES ('Standart', 5.99);
INSERT INTO tickettypes (ticketName, typePrice) VALUES ('VIP', 10.99);
INSERT INTO tickettypes (ticketName, typePrice) VALUES ('Chungus Pass', 11.99);
INSERT INTO `events` (`id`, `eventName`, `eventDescription`, `eventCategory`, `eventDate`, `eventLocation`, `eventImage`, `eventBanner`, `eventCapacity`, `seatsRequired`, `createdAt`, `updatedAt`) VALUES (1, 'Ziedu mēness slepkavas', '20. gs. mijā nafta atnesa bagātību oseidžu ciltij, kuri vienā naktī kļuva par bagātākajiem cilvēkiem pasaulē. Tas piesaistīja balto cilvēku uzmanību, kuri ieradās oseidžu zemē, nozaga, cik spēja, pirms ķērās pie slepkavībām. “Ziedu mēness slepkavas” pamatā ir patiess stāsts, kura centrā ir Ernesta un Mollijas attiecības. Mārtina Skorsēzes episkajā vesterna kriminālsāgā mīlestības ceļi krustojas ar neizmērojamu nežēlību.', 1, '2024-02-03', 'Rīgas iela 1, Kino \"Mogus\"', 'https://forumcinemaslv.blob.core.windows.net/1012/Event_10123/portrait_large/Killers-of-the-Flower-Moon_Plakats_1620x2400px.jpg', 'https://media.cinemacloud.co.uk/imageFilm/1577_1_2.jpg', 26, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);